version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@antognoli.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
       - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin 

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:8080"
      - "8001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - catalogdb

  basketdb:
    container_name: basketdb
    ports:
      - "6379:6379"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings:Redis=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc:8080"
    ports:
      - "8002:8080"
      - "8003:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - basketdb

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings:Postgres=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "8004:8080"
      - "8005:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - discountdb

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings:Postgres=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "8006:8080"
      - "8007:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - discountdb
